# Generated by Django 3.1.7 on 2021-04-24 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthdate', models.DateField(blank=True)),
                ('registration_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(max_length=254, verbose_name='Client email')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('name_underscore', models.CharField(max_length=60)),
                ('volume', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.series')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.IntegerField()),
                ('pub_date', models.DateField()),
                ('writer', models.CharField(blank=True, max_length=60)),
                ('penciller', models.CharField(blank=True, max_length=60)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.series')),
            ],
        ),
    ]
