# Generated by Django 3.1.7 on 2021-03-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210328_1712'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='series',
            unique_together=set(),
        ),
    ]
